### ISSUE TITLE
[BUG] - Undefined Error while generating default

### ISSUE THREAD

**Issue by xrazor2k** [vultr/whmcs-vultr#21]
**undefined error while trying to generate default**

1. Setup -> Products/Services -> Products/Services -> Create New Product -> Module Settings -> Configurable Options -> Generate Default
2. Setup -> Products/Services -> Products/Services -> Create New Product -> Module Settings -> Custom Fields -> Generate Default

**WHMCS version : 7.7.1**
 - PHP Version 7.0/7.3
 - Browser FIREFOX v.67.0.4 (64 bits), Chrome v.75.0.3770.100

**Comment by immdraselkhan** [comment]
Did you try with PHP 7.2?

**Comment by ddymko** [comment]
@xrazor2k 

WHMCS-Vultr supports PHP 7.1.x or higher. We will take a look into the reported issue for you.

**Comment by afady** [comment]
Hi @xrazor2k - I haven’t been able to reproduce your issue. When creating a new product, under the module settings tab, make sure to enter your API key in the field labeled `Your API Key` then press the `Save Changes` button. The `Generate default` buttons should work after saving.

If you are still having trouble generating the default options, please make sure you’re using PHP 7.1 or greater and provide a screenshot of the error and any other details that may be relevant to the issue so that we can get this taken care of.

**Comment by xrazor2k** [comment]
> Hi @xrazor2k - I haven’t been able to reproduce your issue. When creating a new product, under the module settings tab, make sure to enter your API key in the field labeled `Your API Key` then press the `Save Changes` button. The `Generate default` buttons should work after saving.
> 
> If you are still having trouble generating the default options, please make sure you’re using PHP 7.1 or greater and provide a screenshot of the error and any other details that may be relevant to the issue so that we can get this taken care of.

Thanks for your fast reply. I have saved & Try to generate again then i still have this error.

Here is the screenshots

Web Browser
![screenshot_bug_whmcs](https://user-images.githubusercontent.com/9898731/60911155-c1bd6400-a2ac-11e9-9b9c-3c009050e181.png)

Chrome Console : 
![screenshot_bug_whmcs_console](https://user-images.githubusercontent.com/9898731/60911162-c4b85480-a2ac-11e9-985b-be73c725d0fb.png)

**Comment by afady** [comment]
@xrazor2k

Thank you for posting those screenshots. We reviewed the module code and we still aren't sure exactly how you're getting an `undefined` error.

Could you please check the Network tab in the Chrome developer tools. When you click either one of the generate buttons, you should see an AJAX request to `configproducts.php?action=edit&id=YOUR_PRODUCT_ID&tab=3` - could you post the response to that request? I have attached an example screenshot below:

![Screen Shot 2019-07-09 at 3 03 34 PM](https://user-images.githubusercontent.com/2603657/60916722-2224b500-a25d-11e9-8fc0-7131b28f0b46.png)
