### ISSUE TITLE
cannot list OSID

### ISSUE THREAD

**Issue by arsenhov1q1q1q** [vultr/whmcs-vultr#25]
hi
on Whmcs 7.7 and php 7.3 we have problem
in client area location listed but client cannot select os type
![vultr2](https://user-images.githubusercontent.com/53305650/61879289-fdad1780-aeaf-11e9-8c74-1e3a32645078.png)

**Comment by breakforme732** [comment]
Hi @arsenhov1q1q1q It looks like you may have missed a step when setting up that product on the admin side. When you create the product for a group, you have to go to the "Module Settings" tab, ensure that the correct API key is entered in the field, (no whitespace), and click "Generate default", please see the screenshot I've included. 
<img width="749" alt="Screenshot (286)" src="https://user-images.githubusercontent.com/25594613/61880991-e5df8e80-aec3-11e9-9c31-b2a2323801c7.png">

**Comment by arsenhov1q1q1q** [comment]
Thank you for responding
but i have problem 
see this images
![vultr2](https://user-images.githubusercontent.com/53305650/61886697-6a7ade80-aebd-11e9-884f-422bb4535d04.png)
![vultr3](https://user-images.githubusercontent.com/53305650/61886706-6ea6fc00-aebd-11e9-8f88-efbc7552daeb.PNG)
![vultr4](https://user-images.githubusercontent.com/53305650/61886720-736bb000-aebd-11e9-81e1-eb06e596affd.PNG)
![vultr5](https://user-images.githubusercontent.com/53305650/61886737-78c8fa80-aebd-11e9-97b7-efe1b1bdc1cd.png)

**Comment by ddymko** [comment]
@arsenhov1q1q1q You posted a screenshot with your Public Vultr API Key. I have removed this photo.

Also I am not entirely sure what the issue is here? Have you tried generating the defaults? 

Also are you running a custom theme on your WHMCS instance? Your pages look inverted.

**Comment by breakforme732** [comment]
Hi @arsenhov1q1q1q

building on what @ddymko mentioned, there are notable styling differences as well. If this is a custom styling, that could be causing the issue

**Comment by arsenhov1q1q1q** [comment]
My Problem resolved by configure "Configurable Options" 
thank you all
![vultr6](https://user-images.githubusercontent.com/53305650/61888389-a95e6380-aec0-11e9-8cda-82ef98855caa.png)

**Comment by ByronAP** [comment]
@arsenhov1q1q1q  did you have to manually add each option?

**Comment by ByronAP** [comment]
i for the life of me can not get the os field to populate... everything else works

**Comment by AnilChinchawale** [comment]
Hello,

Facing same issue where user not able to get configuration form to put information OS and other information, I would request you to guide me to fix it.

**Comment by AnilChinchawale** [comment]
Thanks, it worked!

**Comment by xbh03** [comment]
Hi all, I have the same problem, I can't solve it.
