### ISSUE TITLE
URL Hide on Console window

### ISSUE THREAD

**Issue by Montana357** [vultr/whmcs-vultr#26]
hello, is there a way to mask or hide the url on the client side consule window ?

im trying to implement this module for my whmcs panel but testing out the functions i find out that my clients can guess that im using vultr as provider just looking at the consule popup window url bar

![image](https://user-images.githubusercontent.com/1530302/62582151-68c7f800-b879-11e9-8704-d74a6378d973.png)

**Comment by immdraselkhan** [comment]
I also need to hide this url.

**Comment by ddymko** [comment]
Hey @Montana357 @immdraselkhan 

If you reach out to our billing/support they can enable a whitelisted one for your specific accounts. 

https://my.vultr.com/support/create_ticket/

**Comment by immdraselkhan** [comment]
A ticket has been sent :)
