### ISSUE TITLE
Bug & Help

### ISSUE THREAD

**Issue by immdraselkhan** [vultr/whmcs-vultr#27]
#Bug
Vultr module menu Server Location's font-awesome icon not showing correctly.
Please check this screenshot to better understand: https://prntscr.com/oqjohl

#Help
How DNS (nameservers) works? Have any problems because I have changed to my own domain nameservers?
Screenshot: https://prntscr.com/oqjqau

**Comment by afady** [comment]
Hi @immdraselkhan,

Thanks for reporting the issue with the icon. It's fixed in #28.

Here is some more information on the Vanity Nameservers from https://www.vultr.com/docs/vultr-whmcs-module:
> The Vultr WHMCS Module supports Vanity Nameservers (custom ns1 and ns2.domain.com). Setting up Vanity Nameservers requires a first step, which is to create the custom name servers with your domain registrar and point them to the IPs ns1.vultr.com and ns2.vultr.com resolves to.
> 
> Once done, please follow the steps below:
> 
> 1. Login to your WHMCS Admin Panel.
> 2. Go on Addons -> Vultr Module.
> 3. Click on DNS.
> 4. Add the values for Nameserver 1 and Nameserver 2 and click Save Changes.
> 5. You’re done.
> 
> Please note that Vanity Nameservers are applied to newly added DNS Zones/Domains. Existing ones will have to be modified in https://my.vultr.com manually.

**Comment by immdraselkhan** [comment]
What are the IPs ns1.vultr.com and ns2.vultr.com?

**Comment by immdraselkhan** [comment]
ns1.vultr.com 173.199.96.96
ns2.vultr.com 173.199.96.97
Is that correct?

**Comment by afady** [comment]
@immdraselkhan, yes, I believe that is correct.
