### ISSUE TITLE
[BUG] - In Service Destroy

### ISSUE THREAD

**Issue by maisonmdsgreen** [vultr/whmcs-vultr#30]
When I destroy a machine and want to use the same request to create a new one, operating system selection doesn't work

![vultr-min](https://user-images.githubusercontent.com/11423362/64489645-ec378900-d22b-11e9-9b44-edf1e5e8a6db.gif)

Thanks

**Comment by ddymko** [comment]
@maisonmdsgreen 

Thanks for creating a ticket. We will look into this issue and see what the issue might be

**Comment by breakforme732** [comment]
Hi @maisonmdsgreen 
Can you please be more clear with the exact issue? You said "operating system selection doesn't work", but the screen cap you provided shows the OS selection working. We'd be happy to help with your issue, but are unclear as to what, exactly, the issue is. Thanks.

**Comment by maisonmdsgreen** [comment]
It works but when it saves it always goes back to Application independent of what I save

Example select centos 7x save 

Show aplication not centos 7

Thanks

**Comment by ddymko** [comment]
@maisonmdsgreen I have a question for you. Did you `generate defaults`. It looks like those fields are going to the database to retrieve the data so WHMCS may not have initially generated the `Application` information.

**Comment by maisonmdsgreen** [comment]
I have spawned before.

![aplication](https://user-images.githubusercontent.com/11423362/65167198-7942c500-da18-11e9-83ac-449018018e09.JPG)

![aplication drop](https://user-images.githubusercontent.com/11423362/65167204-7ba51f00-da18-11e9-8e90-3c4bf4f4e434.JPG)

**Comment by ddymko** [comment]
@maisonmdsgreen We are going dig into this. We aren't able to replicate the issue you are having. With the latest code on the master branch.


![app](https://user-images.githubusercontent.com/1588386/65179245-6b953b80-da28-11e9-86a4-dc6631a5b081.png)

**Comment by maisonmdsgreen** [comment]
@ddymko I will try to recreate the problem

**Comment by maisonmdsgreen** [comment]
Try to get an account with another product and switch fot plan VPS and see what happens

Thanks
