### ISSUE TITLE
[Feature] - Other Buttons Translation Option

### ISSUE THREAD

**Issue by maisonmdsgreen** [vultr/whmcs-vultr#32]
I translate the file to my language, but I see many options in English, and it is possible to add these buttons to the translation.

\servers\vultr\template\controller\main\index.tpl

Line 253

`<button class="btn btn-primary" type="submit">Update</button>`

and 263

`<button class="btn btn-default" type="button">Change</button>`

Add example  for 253

`$_LANG['main']['index']['label_update'] = 'Update';`

and

And use `$_LANG['main']['index']['label_change'] = 'Change';` for 263

Thanks

**Comment by ddymko** [comment]
This was updated and released in v2.0.3
