### ISSUE TITLE
[Feature] - Remove Any vultr Name and url from template

### ISSUE THREAD

**Issue by Jawanet** [vultr/whmcs-vultr#35]
Hi

To make fully whitelable, please remove vultr name from url and template

Thank you

**Comment by ddymko** [comment]
@Jawanet 

Which URL and Template are you referring to?

**Comment by Jawanet** [comment]
From main template, default dns should empty

**Comment by ddymko** [comment]
@Jawanet you can add in a vanity nameserver which will remove the vultr name.

Please see:
https://github.com/vultr/whmcs-vultr/issues/27#issuecomment-519960414

**Comment by ddymko** [comment]
relates to #
