### ISSUE TITLE
Module does not create automatically configurable options

### ISSUE THREAD

**Issue by brasileirodacosta** [vultr/whmcs-vultr#37]
Hello good afternoon!

I installed the vultr module on my whmcs today, but it turns out that it did not automatically create options to choose the OS system or applications already installed.

**Comment by ddymko** [comment]
@brasileirodacosta 

You have to manually generate the defaults for configurable options

**Comment by ddymko** [comment]
https://github.com/vultr/whmcs-vultr/issues/21#issuecomment-509215907

**Comment by brasileirodacosta** [comment]
Thanks, it worked!
