### ISSUE TITLE
[Feature] - Require Simple, intuitive and fully responsive WHMCS theme

### ISSUE THREAD

**Issue by AnilChinchawale** [vultr/whmcs-vultr#39]
**Describe the solution you'd like**
As of now UI is basic with advance features, I would appriciate if you can ADD UI like https://lagom.rsstudio.net where user feel same with advance UI.

**Comment by Hostground** [comment]
Please see https://lagom.rsstudio.net/extensions/whmcs-modules-integration/vultr

**Comment by AnilChinchawale** [comment]
I have purchased it already and using it, I request you to provide it by default.

**Comment by Hostground** [comment]
> I have purchased it already and using it, I request you to provide it by default.

This is also something theme related, different themes require a different style. 

We must give the developers also some credit to maintain the template. This module is already free of charge.

**Comment by AnilChinchawale** [comment]
Thank you...!!!
