### ISSUE TITLE
Bug na hora de finalizar pedido de VPS

### ISSUE THREAD

**Issue by brasileirodacosta** [vultr/whmcs-vultr#41]
Olá, boa tarde!

Na hora que vou finalizar um pedido de uma VPS, no pedido eu marco que eu não quero backup automático, mas por algum motivo quando eu pago o pedido e vou no serviço ele mostra que está com o backup automático ativado. Antes de atualizar ele para a versão 2.0.4 ele não fazia isso.

**Comment by ddymko** [comment]
Hey there @brasileirodacosta 

Could you please try version 2.0.3 again? We did not make any changes that would affect backups.

The only changes that was made for `2.0.4` was https://github.com/vultr/whmcs-vultr/pull/36/files
