### ISSUE TITLE
Not Generating Configurable Options

### ISSUE THREAD

**Issue by empmdk** [vultr/whmcs-vultr#42]
I've installed the WHMCS module & from what I've read it is supposed to generate configurable options on its own. None are being generated.
When I add a VPS service to a user & go to create an instance, the ISO drop-down is grayed out. I'm able to select everything but that & does not allow me to proceed further.

**Comment by breakforme732** [comment]
Hi @empmdk The defaults for the configurable options have to be generated manually. Please see https://github.com/vultr/whmcs-vultr/issues/21#issuecomment-509215907

**Comment by empmdk** [comment]
I have generated configurable options & custom fields. I'm able to make a selection when adding a service to a client. However, while logged in as a client, I'm unable to select an OS. It is stuck on whatever was chosen on the "Add New Order" page. Is this by design to not allow clients to change the OS or am I missing something?
I am able to change it on the administration side.

![Client-Cannot-Choose-OS](https://user-images.githubusercontent.com/6612031/66575257-9fedaa80-eb43-11e9-9bac-5c247e8db87a.png)
