### ISSUE TITLE
[BUG] - Module settings tab is not working

### ISSUE THREAD

**Issue by tinof** [vultr/whmcs-vultr#43]
**Describe the bug**
Editing a product created by this extension does not work as expected (module settings).

**To Reproduce**
1. Add a single Vultr product as instructed in https://www.vultr.com/docs/vultr-whmcs-module
2. Setup -> Products/services -> Edit Vultr Product

**Expected behavior**
This should not get stuck / I should be able to generate the default configurable options for example.

**Screenshots**
Setup -> Products/services -> Edit Vultr Product: https://i.imgur.com/bjbgK3e.png
Chrome Inspect (shows errors): https://i.imgur.com/RQ4ujua.png

Windows 10 with Chrome

Server has Nginx 1.17.4, PHP 7.3.x, MariaDB 10.4.x, WHMCS 7.8.3, latest Vultr module as of today.

**Comment by ddymko** [comment]
@tinof 

We weren't able to replicate it on our test environments but we will spend some more time digging into the errors you posted and hopefully we can find the culprit
