### ISSUE TITLE
[BUG] -Wrong version number

### ISSUE THREAD

**Issue by NesooseN** [vultr/whmcs-vultr#45]
After last update to and also in previous updates, in WHMCS Addon section, it always show 1.0.0 version - https://s3.amazonaws.com/upload.screenshot.co/45636feafb

Please fix it.

**Comment by breakforme732** [comment]
Hello @NesooseN it appears that you may be using an old version of the module. Please follow the readme to update to the latest version of the module.

<img width="412" alt="Screenshot (323)" src="https://user-images.githubusercontent.com/25594613/67689105-38bc5c80-f971-11e9-86fd-eee22133c728.png">
