### ISSUE TITLE
[BUG] - Unable to pull all Configurable Option, only some

### ISSUE THREAD

**Issue by P-X-L** [vultr/whmcs-vultr#52]
Hello, 

Glad to see this being developed. 

When I generate defaults under product, then go to the auto-generated options, there is only 4 options which were imported. 

![image](https://user-images.githubusercontent.com/12635648/69349385-f0dedb80-0c77-11ea-9382-38c1fcb0c589.png)

I'm unable to get Regions and IP setting fields to propagate.

**Comment by P-X-L** [comment]
Anyone having the same issue?

**Comment by ddymko** [comment]
@P-X-L 

We are unable to replicate this issue. You should have the full list when you autogenerate the options.

It may help if you take a look at
https://github.com/vultr/whmcs-vultr/issues/51#issuecomment-549375508

**Comment by P-X-L** [comment]
IPV6 wasn't properly whitelisted...
Please continue on improving this module :)
