### ISSUE TITLE
[BUG] - username field missing 

### ISSUE THREAD

**Issue by Hostground** [vultr/whmcs-vultr#53]
**Describe the bug**
The username field is missing inside whmcs. 

**To Reproduce**
Create a server. (windows example) 
Open the server information inside whmcs as a client. 
Notice there is no username field 

**Expected behavior**
That the username is present inside the server details information.

**Comment by breakforme732** [comment]
Hey @Hostground 
The username is going to be default. For your example specifically, (windows), the username is displayed when the console is logged into.
