### ISSUE TITLE
[BUG] -Unable to select os - resulting OSID error on creation

### ISSUE THREAD

**Issue by terply** [vultr/whmcs-vultr#55]
from the client's panel trying to set up a new VPS
The OS selection box is unavailable which results in not being able to set up the server.
WHMCS V.7.8.3
PHP V 7.2
FireFox Version 71.0 (64-bit)
NO IPV6
IPV4 - whitelisted
![vultr-error1](https://user-images.githubusercontent.com/56179678/71596438-53878a80-2af4-11ea-80c8-8cc41bfbd830.png)
![vultr-error2](https://user-images.githubusercontent.com/56179678/71596478-6b5f0e80-2af4-11ea-87bb-e2cdd37782df.png)

Any help would be greatly apreciated.

**Comment by breakforme732** [comment]
@terply 

We are unable to replicate this issue. You should have the full list when you autogenerate the options.

It may help if you take a look at
https://github.com/vultr/whmcs-vultr/issues/51#issuecomment-549375508
