### ISSUE TITLE
[Feature] - cPanel dynamic pricing

### ISSUE THREAD

**Issue by eran101** [vultr/whmcs-vultr#58]
cPanel changed their pricing to active accounts pricing.
The Vultr WHMCS Module allows only one price for the cPanel "application".
This should be updated to the current pricing and support over 100 accounts.
The pricing is available in the middle of the page on the following link:
https://www.vultr.com/apps/cpanel

**Comment by breakforme732** [comment]
The pricing of applications is set in the configurable options area of the admin area. Please be sure to follow the documentation fully when setting up the module.
