### ISSUE TITLE
[BUG] - A VPS is not listed after it was created

### ISSUE THREAD

**Issue by eran101** [vultr/whmcs-vultr#59]
When a VPS is created, it's not listed in the client area.
Instead, the client can create more VPS.
This was tested with the latest versions WHMCS and Vultr Module for WHMCS.

**Comment by breakforme732** [comment]
Hello @eran101 

Please provide a detailed reproduction of this bug, as our team was unable to reproduce this issue in testing

**Comment by eran101** [comment]
WHMCS 7.8.3
PHP 7.2
Vultr Module for WHMCS 2.0.4

A client makes a Vultr VPS order on WHMCS.
The client sets the password and other details on the order page.
Then, in the client area, he creates a VPS.
The VPS is created in the Vultr account on vultr.com
The client still has an option to create a VPS again and again in the client area.
I have screencasts showing this.
Wouldn't like to share in publicly so please get the link from Vultr Ticket #VZO-61HLU

**Comment by breakforme732** [comment]
Hey @eran101 

I watched your screen capture video from the ticket, and it doesn't seem to show anything but an instance being created, which is the expected behavior

**Comment by eran101** [comment]
> Hey @eran101
> 
> I watched your screen capture video from the ticket, and it doesn't seem to show anything but an instance being created, which is the expected behavior

There was an issue with the screencast.
You don't see the the WHMCS client area if you noticed.
I will send a new one and update.
Thanks!

**Comment by eran101** [comment]
> Hello @eran101
> 
> Please provide a detailed reproduction of this bug, as our team was unable to reproduce this issue in testing

Another user had this issue:
https://github.com/vultr/whmcs-vultr/issues/62

**Comment by eran101** [comment]
I updated the Vultr Ticket #VZO-61HLU with a link to the new screencast.
