### ISSUE TITLE
[BUG] - Random password is set when the VPS is created

### ISSUE THREAD

**Issue by eran101** [vultr/whmcs-vultr#60]
In the WHMCS order process, the client is asked to provide a password for the VPS.
When the VPS is created, some random password is set automatically.
The VPS password is different than the client provided password.

**Comment by breakforme732** [comment]
Hello @eran101 

Can you please provide a reproduction of this bug? We were unable to reproduce this issue in multiple tests.

**Comment by eran101** [comment]
WHMCS 7.8.3
PHP 7.2
Vultr Module for WHMCS 2.0.4

A client makes a Vultr VPS order on WHMCS.
The client sets the password and other details on the order page.
Then, in the client area, he creates a VPS.
The VPS is created in the Vultr account on vultr.com
When checking the VPS password after it was created on the vultr.com acccount, it has a different root password.
I have screencasts showing this.
Wouldn't like to share in publicly so please get the link from Vultr Ticket #VZO-61HLU

**Comment by eran101** [comment]
> I have screencasts showing this.
> Wouldn't like to share in publicly so please get the link from Vultr Ticket #VZO-61HLU
There was an issue with the screencasts I sent. It's not showing the WHMCS side.
I will send a new screencast and update the ticket.

**Comment by eran101** [comment]
I updated the Vultr Ticket #VZO-61HLU with a link to the new screencast.

**Comment by Hostground** [comment]
This is stated in the docs, the api creates a password not whmcs.

**Comment by zylntxx** [comment]
I think you can find the answer in the [document](https://www.vultr.com/docs/vultr-whmcs-module)

**Please keep in mind that the selected root password in the order for will not be used since Vultr’s API will generate a random secure password for each VM**
![image](https://user-images.githubusercontent.com/42884704/72363353-b05b8580-372f-11ea-9a8f-d46d30334d26.png)
