### ISSUE TITLE
SUPPORT LINK IN APPLICATION DETAILS

### ISSUE THREAD

**Issue by BeezyIV** [vultr/whmcs-vultr#61]
CHALLENGE
When a user signs up and sets up an instance, the Application Information is displayed in the client area. However, the support link that is indicated in the details point to Vultr support instead of the re-seller's support hub.

Is it possible to change this link to a custom link or totally conceal it from the client?

Kindly refer to the screenshot below in relation to a VPS with cPanel on CentOS 7.

![App Details](https://user-images.githubusercontent.com/34535237/71717522-0885b400-2e21-11ea-845b-608d12b2c16a.JPG)

**Comment by breakforme732** [comment]
Hey @BeezyIV 

It looks like you need to have your Vultr account white-labelled as a reseller. Please submit a ticket through the members portal requesting this for your account.

**Comment by BeezyIV** [comment]
Hello @breakforme732 
Thanks for the assist. Let me try doing just that.

**Comment by BeezyIV** [comment]
Hey @breakforme732 
The support team confirms that they have white-labelled my account as a resseller account but the case is still the same. I am still getting the Vultr support link.
