### ISSUE TITLE
[BUG] - An error while trying to reboot an existing VPS from WHMCS admin area.

### ISSUE THREAD

**Issue by eran101** [vultr/whmcs-vultr#66]
**Describe the bug**
I get an error while trying to reboot an existing VPS from the WHMCS admin area.
The Vultr VPS doesn't reboot.
The error is: 

> Module command error
> VPS ID not found

**To Reproduce**
1. Go to the WHMCS admin area.
2. Click on the client.
3. Click on the Vultr VPS product.
4. Click reboot.

**Expected behavior**
The VPS should actually reboot without an error.

**Screenshot**

![Annotation 2020-01-22 193127](https://user-images.githubusercontent.com/3607852/72919113-91707b00-3d4f-11ea-82c2-c16de44295a9.jpg)

 - OS: CentOS 7
 - Apache HTTP server 2.4
 - PHP 7.3 
 - WHMCS 7.9.1
 - Vultr WHMCS Module 2.0.4

**Comment by breakforme732** [comment]
Hello @eran101 

If you are receiving this error, something was configured incorrectly during the setup of the module. Please ensure that everything is configured properly.
