### ISSUE TITLE
[BUG] - Enter a descriptive title

### ISSUE THREAD

**Issue by 997862** [vultr/whmcs-vultr#68]
I open VPS of vultr through WHMCS, and the host is open, but WHMCS shows that the host is not open, so it cannot be managed for the host. When we visit the vultr module, the overall speed of the website will be very slow, generally a visit takes more than 1 minute. I use version 7.9.1 of WHMCS.

**Comment by 997862** [comment]
<img width="1235" alt="001" src="https://user-images.githubusercontent.com/1093092/73469018-a89f1080-43c0-11ea-9a8a-298ce57d35c1.png">
<img width="953" alt="002" src="https://user-images.githubusercontent.com/1093092/73469029-ae94f180-43c0-11ea-8c5e-7c12d90aff23.png">

**Comment by breakforme732** [comment]
I'm unable to reproduce a speed issue. This could be caused by several issues, including your internet speed.
