### ISSUE TITLE
[BUG] - Once VPS Created, Doesn't Sync with Account

### ISSUE THREAD

**Issue by nikok913** [vultr/whmcs-vultr#70]
Hi, so I created a VM. Then, when I the VPS was done being created, I went onto the client are and saw that it didn't recognize that it had been created, however it had been created on my vultr account side. I believe this is a glitch. I followed everything perfectly in installation instructions. 

https://gyazo.com/12f2faa717ba178ffc19e3969172b3b0

**Comment by eran101** [comment]
If the VPS was created via the client area Vultr WHMCS module, it may be due to a missing custom field:

> subid|Virtual machine ID


That's what I found out.
@ddymko

**Comment by ddymko** [comment]
@nikok913 
Thank you for your problem report and sorry to hear you are having an issue! I've reviewed the content in this issue and noticed some of it is incomplete and this may prevent our contributors from being able to successfully reproduce your error.

Please take a moment to summarize all the necessary data in a new issue report that follows our bug reporting guidelines. I've included these below for your convenience

```
**IMPORTANT: WHMCS errors are difficult to reproduce and troubleshoot unless we have a very detailed problem report. Please note that incomplete reports may be REJECTED as incomplete**

In order to help community members to reproduce your error, your bug must occur on a newly installed instance as described in our public documentation -  https://www.vultr.com/docs/vultr-whmcs-module#Installation - no other plugins or configurations should be present.


**Describe the bug**
A clear and concise summary of what the bug is, and the fixes you’ve attempted.

**Your Environment:**
 - Server PHP Version [e.g. PHP7, Go 1.12]
 - Server Operating System and Version
 - WHMCS Version [e.g. 22]
 - Your desktop OS: [e.g. iOS] + Browser version [e.g. stock browser, safari]

**Detailed steps to reproduce error on fresh install**
For example:
1. Login to '...' 
2. Configure ‘...’
3. Click on menu option '....'
3. Scroll down to '....'
4. See error (Add screenshots and logs that may help explain your problem)

**Logs**
Provide error logs from WHMCS - go to Utilities>Logs>Module Log

**Additional Logs and Extra Information**

Add any other context about the problem here.
```
