### ISSUE TITLE
Issue - Not able to use  vultr WHMCS

### ISSUE THREAD

**Issue by sufiyanshaikh12** [vultr/whmcs-vultr#71]
Not able to use vultr api from WHMCS.
Getting "HTTP Code: 403 Invalid API key" when debug mode in whmcs is "on".

I have white listed all ipv4 and also ipv6 in my vultr api setting.
IP key is correct and also tried generating new key
I have off firewall which may create issue.

Please help

**Comment by sufiyanshaikh12** [comment]
![vultrr](https://user-images.githubusercontent.com/39752010/75963285-35bb1500-5eeb-11ea-8de6-67d1b15cfdb3.png)

**Comment by BeezyIV** [comment]
Hello,
In your WHMCS, go to Utilities>Logs>Module Log. Under response, look for the IPv4 or IPv6 address being displayed as not having access to your Vultr API, copy it and whitelist it in your Vultr account instead. Your server IP is usually not the same as your WHMCS IP.

**Comment by sufiyanshaikh12** [comment]
curl -H 'API-Key: YOURKEY' "https://api.vultr.com/v1/server/list"

This command is working fine on ssh of that server and giving list of servers in my account with the same key which is showing wrong in WHMCS  

My WHMCS version :  7.9

Also have got a mail for cron not working and "vutlr" module creating issues due to bugs in code.
I request Vultr team to fix it and make compatible with the latest versions of WHMCS.

**Comment by sufiyanshaikh12** [comment]
> Hello,
> In your WHMCS, go to Utilities>Logs>Module Log. Under response, look for the IPv4 or IPv6 address being displayed as not having access to your Vultr API, copy it and whitelist it in your Vultr account instead. Your server IP is usually not the same as your WHMCS IP.

When I was using older version of WHMCS, the vultr module was working fine.
Well, I am a hosting provider and WHMCS is hosted on same server with same shared IP.
Before opening this bug report, I did make sure I have tried all possible ways to solve this issue including allowing all IPv4 IP's and also IPv6 too
![allowed](https://user-images.githubusercontent.com/39752010/75964059-94cd5980-5eec-11ea-99f9-085664c959ad.png)

**Comment by BeezyIV** [comment]
What error is your WHMCS Module Log giving?

**Comment by sufiyanshaikh12** [comment]
> What error is your WHMCS Module Log giving?

Already attached in above replies
![vultrr](https://user-images.githubusercontent.com/39752010/75965095-5042bd80-5eee-11ea-8a0f-e3ca23730f0a.png)

**Comment by sufiyanshaikh12** [comment]
Error which was received when cron job failed.




PHP Fatal error:  require_once(): Failed opening required '/home/username/domains/my.domain.com/public_html/modules/servers/vultr/helper/vultr.helper.php' (include_path='.:/opt/alt/php73/usr/share/pear') in /home/username/domains/my.domain.com/public_html/modules/addons/vultr/hooks.php on line 6
[WHMCS Application] ERROR: Whoops\Exception\ErrorException: require_once(): Failed opening required '/home/username/domains/my.domain.com/public_html/modules/servers/vultr/helper/vultr.helper.php' (include_path='.:/opt/alt/php73/usr/share/pear') in /home/username/domains/my.domain.com/public_html/modules/addons/vultr/hooks.php:6 Stack trace: #0 /home/username/domains/my.domain.com/public_html/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(64, 'require_once():...', '/home/username...', 6) #1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown() #2 {main} {"exception":"[object] (Whoops\\Exception\\ErrorException(code: 64): require_once(): Failed opening required '/home/username/domains/my.domain.com/public_html/modules/servers/vultr/helper/vultr.helper.php' (include_path='.:/opt/alt/php73/usr/share/pear') at /home/username/domains/my.domain.com/public_html/modules/addons/vultr/hooks.php:6)"} []
Whoops\Exception\ErrorException: require_once(): Failed opening required '/home/username/domains/my.domain.com/public_html/modules/servers/vultr/helper/vultr.helper.php' (include_path='.:/opt/alt/php73/usr/share/pear') in /home/username/domains/my.domain.com/public_html/modules/addons/vultr/hooks.php:6

#0 /home/username/domains/my.domain.com/public_html/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(64, 'require_once():...', '/home/username...', 6)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}

**Comment by breakforme732** [comment]
@sufiyanshaikh12  it looks like an error in the module itself communicating with the vultr API. I'm certain they will fix this promptly. For the meantime, however, I'd recommend resetting that api whitelist, as allowing all ipv4 and IPv6 addresses seems unsafe.

**Comment by sufiyanshaikh12** [comment]
> @sufiyanshaikh12 it looks like an error in the module itself communicating with the vultr API. I'm certain they will fix this promptly. For the meantime, however, I'd recommend resetting that api whitelist, as allowing all ipv4 and IPv6 addresses seems unsafe.

I hope they fix it promptly.
Just for testing I allowed all pv4 and IPv6.
I have already disabled it as the results are out and its confirmed that this is issue of vultr whmcs module

**Comment by ddymko** [comment]
@sufiyanshaikh12 

Thank you for your problem report and sorry to hear you are having an issue! I've reviewed the content in this issue and noticed some of it is incomplete and this may prevent our contributors from being able to successfully reproduce your error. 

Please take a moment to summarize all the necessary data in a new issue report that follows our bug reporting guidelines. I've included these below for your convenience


```
**IMPORTANT: WHMCS errors are difficult to reproduce and troubleshoot unless we have a very detailed problem report. Please note that incomplete reports may be REJECTED as incomplete **

In order to help community members to reproduce your error, your bug must occur on a newly installed instance as described in our public documentation -  https://www.vultr.com/docs/vultr-whmcs-module#Installation - no other plugins or configurations should be present.


**Describe the bug**
A clear and concise summary of what the bug is, and the fixes you’ve attempted.

**Your Environment:**
 - Server PHP Version [e.g. PHP7, Go 1.12]
 - Server Operating System and Version
 - WHMCS Version [e.g. 22]
 - Your desktop OS: [e.g. iOS] + Browser version [e.g. stock browser, safari]

**Detailed steps to reproduce error on fresh install**
For example:
1. Login to '...' 
2. Configure ‘...’
3. Click on menu option '....'
3. Scroll down to '....'
4. See error (Add screenshots and logs that may help explain your problem)

**Logs**
Provide error logs from WHMCS - go to Utilities>Logs>Module Log

**Additional Logs and Extra Information**

Add any other context about the problem here.
```

**Comment by sufiyanshaikh12** [comment]
Its a fresh whmcs installation and no other module is present in WHMCS.

Connection to vultr api is not able to be made with WHMCS vultr module.

The issue is that the module is not getting connected with Vultr with whmcs vultr module.
Fixes I tried: 
1) Regenerated API key from vultr and updated api key in WHMCS.
2) Allowed **all IPv4 and IPv6** connections from Vultr api settings and also tried **only allowing server IPv4 and IPv6** 
3) Verified if there is any firewall issue by disabling server and other firewall
4) Tired to connect with vultr module from "ssh" and the connection was 'successful'
5) Enabled Debugging in WHMCS and in error log I got message "**HTTP Code: 403 Invalid API key**" however the **_same key was working when tried in SSH_**.

**Your Environment:**
 - Server PHP Version 7.4
 - CloudLinux 7.7
 - WHMCS Version 7.9
 - Your desktop OS: Windows 10 + Google Chrome: Version 80.0.3987.132 (Official Build) (64-bit)

**Detailed steps to reproduce error on fresh install**

1. Install WHMCS and the install vultr WHMCS module. 
2. All all IPv4 and IPv6 
3. Create VPS "product" in whmcs using vultr
4. Allow server IP in vultr api settings.
5. Create VPS and the connection won't be made.
6. Enable debugging.
7. See error (Add screenshots and logs that may help explain your problem)

**Logs**
"HTTP Code: 403 Invalid API key"
![75963285-35bb1500-5eeb-11ea-8de6-67d1b15cfdb3](https://user-images.githubusercontent.com/39752010/76833459-638c4c00-6851-11ea-9db0-212d2373fb98.png)
