### ISSUE TITLE
[BUG] - OS Field Greyed Out In Client Area

### ISSUE THREAD

**Issue by csmith0404** [vultr/whmcs-vultr#73]
I noticed that when one of my clients attempted to start a cloud server, he couldn't edit the OS dropdown menu.

I was eventually able to get CentOS to show up in the dropdown, but I still cannot change the OS option. I have generated the default fields and configurable options, along with updating my API key.

**I can edit the OS in the admin panel, but that is the only way I am able to do so.**

Screenshot:
![3-8-20](https://user-images.githubusercontent.com/52638603/76168223-018e6100-6144-11ea-942f-9c77fbf3135a.PNG)

**Comment by LectorRSS** [comment]
Same error here.

**Comment by arunpyasi** [comment]
Same error here too. Can't get what the issue is.

**Comment by arunpyasi** [comment]
Any update please ?

**Comment by csmith0404** [comment]
As somewhat of a temporary fix, it seems that if you autogenerate all configurable options and input fields, OS/application options are at least present while a client is purchasing.

**Comment by spairo** [comment]
Any update please ?

**Comment by trionnsys** [comment]
same error

**Comment by zachkinsey** [comment]
Same

**Comment by SaneChoice** [comment]
I am not sure, but this restriction might be intentional as different Operating Systems might have a different charge.  

For example, your client might end up ordering a certain Operating System and paying for that.  When they come to the point of deployment in the Admin Panel, they could change the Operating System (i.e. to Windows) but only be paying for a LINUX flavour. 

Maybe this was locked down to prevent that sort of issue?

**Comment by zachkinsey** [comment]
> I am not sure, but this restriction might be intentional as different Operating Systems might have a different charge.
> 
> For example, your client might end up ordering a certain Operating System and paying for that. When they come to the point of deployment in the Admin Panel, they could change the Operating System (i.e. to Windows) but only be paying for a LINUX flavour.
> 
> Maybe this was locked down to prevent that sort of issue?

No idea.

But, because of this inconvenience, I'll have to use a DigitalOcean module instead, since that one works as expected.

Going through the checkout for a vultr VPS, I don't see anything related to having the client select their operating system. 

But, that could be because I don't have configurable options set up for the vultr vps module.

**Comment by SaneChoice** [comment]
Hi @zachkinsey
 
> Going through the checkout for a vultr VPS, I don't see anything related to having the client select their operating system.

That works on our installation.  And I agree its to do with the configurable options.  Have a look at https://clients.sanechoice.com/cart.php?gid=31 , pick a VPS and go through the process.  You can see Application and Operating System during sign-up process. 

However, I agree that once you have purchased and signed up, their seems to be no options to alter your Operating Systems.  Its just greyed out and 'stuck' with what you purchased.

**Comment by SaneChoice** [comment]
I think the below is pretty telling - looks like its disabled by default AFTER you purchase. (Notice the **DISABLED CLASS**).

`<select disabled class="form-control" id="vultrOSID" name="vultrOSID">`

**Comment by zachkinsey** [comment]
> Hi @zachkinsey
> 
> > Going through the checkout for a vultr VPS, I don't see anything related to having the client select their operating system.
> 
> That works on our installation. And I agree its to do with the configurable options. Have a look at https://clients.sanechoice.com/cart.php?gid=31 , pick a VPS and go through the process. You can see Application and Operating System during sign-up process.
> 
> However, I agree that once you have purchased and signed up, their seems to be no options to alter your Operating Systems. Its just greyed out and 'stuck' with what you purchased.

Hmm, so everything works as normal if the configurable options are set for the OS Type/Application during checkout?

That looks like it explains it then.

I'll have to test it really quick to verify.

**Comment by arunpyasi** [comment]
![image](https://user-images.githubusercontent.com/5819908/81528221-eaeecb00-937b-11ea-8903-e35c24cd7ffb.png)
I don't have any option but "1" . Can't select any OS. Need fix please..

**Comment by jose2016** [comment]
Solved:
![](https://i.imgur.com/P9LSzJg.png)
1. Click in Setup/Products/Configurable Options
![](https://i.imgur.com/Y6zgLmQ.png)
2. Select Configurable Option Groups
3. Configurable Options > os_type|OS Type click in edit 
![](https://i.imgur.com/5tzPNB8.png)

And select Option type: Radio
