### ISSUE TITLE
[BUG] - Server not available to be deployed

### ISSUE THREAD

**Issue by cojocariuovidiu** [vultr/whmcs-vultr#74]
what will happen if somebody will buy a server from me using WHMCS and you guys do not have it ?

**Greetings,

If the host node is out of capacity, no one will be able to deploy large instances there. This is true regardless of how the deployment is attempted (Vultr control panel, Vultr API, cPanel, WHMCS API, or any other methods).**

================================================================
The process is the following

New Server Scenario:
1. Customer goes on my WHMCS page -sees a server he can buy
2. He selects the Application - let's say WordPress
3. He is redirected to checkout - pays.
4. After he pays he can deploy the server from the Vultr Module - client side ( API Request )
5. It won't work to deploy ( Customer thinks is a scam or wants a refund ) - Big Issue.

2 Options:

Option 1
If this is automatic and the server is not available to be deployed at point 5 ( Client receives an error from API )
Client wants a package is not existent - cannot be deployed. ( He cannot see this )
Client already paid so I have to issue refund.

Option 2
If this is manual, first I have to let the client choose his package & location - do not pay for it. I receive the order, I check in Vultr if the server can be bought, I let the user to pay, if is available. If it isn't I have to contact the client tell him is out of stock then I may lose that client or convince him to choose a location where the server is available.

Option 2 Defeats the purpose of the Vultr WHMCS module. ( Automation )

Upgrade Server Scenario:
If client bought first package and after some time, wants to upgrade to a bigger package, It will be an issue again cause the same, he will pay first then upgrade.

**Comment by BeezyIV** [comment]
@cojocariuovidiu this is a great point. I had exactly the same concerns. I also opened a case with regards to this issue #63

**Comment by cojocariuovidiu** [comment]
Notice: Even if the client pays, he will only be able to deploy the server for available locations only.

Ex if a 8GB ram server is available in US and is not in EU. ( If client paid, he will only be able to deploy in US )
