### ISSUE TITLE
Not able to use vultr WHMCS

### ISSUE THREAD

**Issue by sufiyanshaikh12** [vultr/whmcs-vultr#75]
Its a fresh whmcs installation and no other module is present in WHMCS.

Connection to vultr api is not able to be made with WHMCS vultr module.

The issue is that the module is not getting connected with Vultr with whmcs vultr module.
Fixes I tried:

Regenerated API key from vultr and updated api key in WHMCS.
Allowed all IPv4 and IPv6 connections from Vultr api settings and also tried only allowing server IPv4 and IPv6
Verified if there is any firewall issue by disabling server and other firewall
Tired to connect with vultr module from "ssh" and the connection was 'successful'
Enabled Debugging in WHMCS and in error log I got message "HTTP Code: 403 Invalid API key" however the same key was working when tried in SSH.
Your Environment:

Server PHP Version 7.4
CloudLinux 7.7
WHMCS Version 7.9
Your desktop OS: Windows 10 + Google Chrome: Version 80.0.3987.132 (Official Build) (64-bit)
Detailed steps to reproduce error on fresh install

Install WHMCS and the install vultr WHMCS module.
All all IPv4 and IPv6
Create VPS "product" in whmcs using vultr
Allow server IP in vultr api settings.
Create VPS and the connection won't be made.
Enable debugging.
See error (Add screenshots and logs that may help explain your problem)
Logs
"HTTP Code: 403 Invalid API key"
![75963285-35bb1500-5eeb-11ea-8de6-67d1b15cfdb3](https://user-images.githubusercontent.com/39752010/76856856-31dbab00-687a-11ea-864d-7763257e6b42.png)

**Comment by ddymko** [comment]
@sufiyanshaikh12 Make sure there is no whitespace. A lot of the time there may be whitespace before or after the API key when it is entered. Which it says invalid API key

**Comment by sufiyanshaikh12** [comment]
Hello,

I have cross checked and there is no whitespace before or after the vultr API key

**Comment by sufiyanshaikh12** [comment]
Hello,

I tried debugging again and this time I got error that IPv6 is not allowed to access the API call.
Allowed the server IPv6 and its WORKING!!!

I literally din't change anything and just enabled the module and then tried to troubleshoot again and damn, its working!

Are you guys sure your API was not down  when I created this : https://github.com/vultr/whmcs-vultr/issues/71

**Comment by ddymko** [comment]
No the API hasn't had any outages
