### ISSUE TITLE
[BUG] - Select OS Type Field Disabled During VPS Creation?

### ISSUE THREAD

**Issue by zachkinsey** [vultr/whmcs-vultr#81]
I don't think this is a bug, because I don't expect there to be a selection for Snapshots or ISOs that are non-existent.

However, the field doesn't display Vultr Applications or a list of all available OS Images.

I read this in the WHMCS module documentation at the bottom~

**How do I update the applications in the configuration options?**

"If you want to list all available applications, you can use this API Command and add the applications you want in the configurable options. Automatic synchronization does not exist in the module."

This implies to me that I need to connect to the vultr API to pull the 'Application' list into the 'Select OS Type' field??

I don't know, I'm not a developer.

And, perhaps the better question is.... why isn't this built into the module... if it is indeed true that you have to pull the application list from the API.

Also, this still doesn't explain it not listing the available OS Images by default.

**Your Environment:**
- PHP Version 7.2.24
- Ubuntu 0.18.04
- WHMCS Version 7.9.2
- Windows 10, Chrome

**Detailed steps to reproduce error on fresh install**
For example:
1. Order a Vultr VPS as a client.
2. During VPS creation, be mad that the 'Select OS type' field is disabled because you can't create a VPS.

Here's the field that stays disabled: http://prntscr.com/s34cpv

**Comment by SaneChoice** [comment]
Hi zachkinsey,

Are you talking about the ordering process and the Operating System and Applications shown in the screenshot below?

<img width="866" alt="Screenshot 2020-04-27 at 12 30 35" src="https://user-images.githubusercontent.com/64412037/80367440-025d8c80-8883-11ea-9152-c2bf93149e94.png">

**Comment by zachkinsey** [comment]
I believe so.

After the ordering process, you're able to finish the VPS set up.

The 'OS Type' field remains disabled.

I'm having the same problem that these guys outlined: https://github.com/vultr/whmcs-vultr/issues/73

**Comment by SaneChoice** [comment]
Thanks @zachkinsey.  I have just responded in that thread.  There could be a reason why they do this on person.  Some Cost/Size mismatch if people change their Operating System after paying?

**Comment by jose2016** [comment]
Solved:
![](https://i.imgur.com/P9LSzJg.png)
1. Click in Setup/Products/Configurable Options
![](https://i.imgur.com/Y6zgLmQ.png)
2. Select Configurable Option Groups
3. Configurable Options > os_type|OS Type click in edit 
![](https://i.imgur.com/5tzPNB8.png)

And select Option type: Radio

**Comment by willvin313** [comment]
I also noticed when you set it to Option type: Radio and save, then revert it to Option type: Dropdown and save it, it works perfectly.
