### ISSUE TITLE
Product configurable options already exist!

### ISSUE THREAD

**Issue by mmagdy88** [vultr/whmcs-vultr#93]
Hello,

I've had an old installation of vultr addon but I removed it then installed the latest one v2.0.4, cleaned up the old files/entries before installing the new version, API connection succeeded, added products, but when I try to Generate Defaults for Configurable options I get the message of:
`Product configurable options already exist!`
Although I don't have any present configuration of the addon and the API is correctly added and working.

**Environment:**
PHP 7.3.23
CentOS 7.x
WHMCS v8.0.2
Chrome on Windows 10

**Steps to reproduce:**
Products/Services -> Edit Product -> Module Settings -> Configurable Options -> Generate default

**Module Log:**
```
HTTP Code: 200
{"balance":"XXXXX","pending_charges":"XXXX","last_payment_date":"XXXX","last_payment_amount":"XXXX"}
```

**Comment by ambirbiar** [comment]
I had EXACTLY the same problem. I decided to reinstall all the whmcs and right after the vultr module. Now the links to create the necessary fields are gone.

PHP 7.3.23
CentOS 7.x
WHMCS v8.0.2

![image](https://user-images.githubusercontent.com/73458062/97768858-e8885500-1b04-11eb-9da7-1bd24fcd8d22.png)
