### ISSUE TITLE
Selecting the data center location

### ISSUE THREAD

**Issue by ambirbiar** [vultr/whmcs-vultr#99]
**The option to choose the location of the data center is not shown on the order form.**

**Environment:**
PHP 7.3.23 PHP-FM
CentOS 7.x
WHMCS v8.0.2

![1](https://user-images.githubusercontent.com/73458062/97803175-1a91d800-1c27-11eb-960a-7661b29a609f.png)

**Comment by SaneChoice** [comment]
Hi @ambirbiar 

I thought that the selection of Datacenter was only available post purchase.  i.e. once you purchase and then go into the activated service, you can pick the datacenter at build time.

**Comment by ambirbiar** [comment]
I didn't check it - its correct see

![1](https://user-images.githubusercontent.com/73458062/97804148-b1ad5e80-1c2c-11eb-9002-c656a8631f6d.png)
